### PR TITLE
Fix indentation and add missing note for propertyName horizontalProjecti...

### PR DESCRIPTION
**Pull request by vog**
...onlocation

### CODE REVIEW

**Comment by ttho** [comment]
Fine with me.

**Comment by porosnie** [comment]
This is not an editorial error. It is a bug in the current AIXM 5.1 schema. The TextPropertyNameType has a pattern of "[a-z][A-Za-z]*" inherited from TextPropertyNameBaseType. This pattern does not allow to store all the AIXM properties like: Service.call-sign, horizontalProjection_location, etc. 

This will be corrected in AIXM 5.1.1. Until then, the only work-around is to leave these property names as they are.

**Comment by vog** [comment]
I think there is a misunderstanding here. I did not propose to change the `aixm:propertyName` to the underscore variant in any way (which would indeed be a schema violation in AIXM 5.1).

This change is all about whitespace characters and XML comments, which is why I marked it as editorial.

I merely fixed the indentation by removing some newline and tab characters from the contents of the `<aixm:propertyName>` tags. In addition, I inserted the explaination comment to _every_ occurrence of "horizontalProjectionlocation". Before, it was only explained at the first occurrence.

Maybe it helps to review this change with a lower tab size in GitHub (by adding `?ts=2` to the URL):

https://github.com/aixm/donlon/pull/14/files?ts=2

**Comment by porosnie** [comment]
Sorry, you are right. I misread your proposal. I think that it is OK to commit, it is indeed an editorial correction only!

**Pull request merged**
