### PR TITLE
Fix xsi:schemaLocation declaration (fixes #16)

### LINKED ISSUE #16: xsi:schemaLocation declaration causes validation problems with xerces
The current xsi:schemaLocation includes explicitly the gml, gmd and xlink schema locations. This is not necessary, since they are already imported in the AIXM and basicMessage schema. In addition, xerces reports a validation error - duplicate declaration of elements in the gml namespace.
A shorter schemaLocation declaration would be sufficient:

"xsi:schemaLocation="http://www.aixm.aero/schema/5.1/message http://www.aixm.aero/schema/5.1/message/AIXM_BasicMessage.xsd http://www.aixm.aero/schema/5.1/event http://www.aixm.aero/schema/5.1/event/Event_Features.xsd"

If you agree, could someone create a Pull request with this change?

### PR DESCRIPTION
**Pull request by vog**
The current schema location causes validation problems with Xerces.

This pull request fixes #16.

### CODE REVIEW

**Comment by porosnie** [comment]
Could we have the support of someone else for this, so that we can commit?

**Comment by vog** [comment]
Any opinions on this?

**Comment by manfredbeckmann** [comment]
I have tested the change with Oxygen XML Editor (uses Xerces for validation) and I support merging the change.

**Comment by vog** [comment]
@porosnie: If you support this, too, feel free to merge it. (According to our rules, I should not merge my own pull request.)

**Pull request merged**
