### PR TITLE
Fix UUID mismatch (#12)

### PR DESCRIPTION
**Pull request by vog**
There were two ways to fix this: Use consistently either UUID "c1bb..." or UUID "5909...".

From the document it was pretty clear that "c1bb..." is the correct UUID.  First, this unit is referenced by "c1bb..." at other places. Second, there is already another feature with UUID "5909...".

### CODE REVIEW

**Comment by porosnie** [comment]
I would like to check this one before committing.

**Comment by vog** [comment]
@porosnie Do you need any additional information from me? Should I point out the relevant Donlon parts which made the situation clear to me?

**Comment by vog** [comment]
Fixed the pull request so it can be merged again. There was a formal conflict with another change that was trivial to solve.

**Comment by porosnie** [comment]
Volker, is this one OK to be committed? Are there no later changes that would conflict with it?

**Comment by vog** [comment]
Yes, it can be merged without any problems. GitHub shows that there are no formal conflicts, and I also don't see any possible non-obvious conflicts. Feel free to merge if you agree with that change.

**Pull request merged**
