### PR TITLE
Use local references instead of abstract references where possible

### PR DESCRIPTION
**Pull request by vog**
These UUIDs are resolvable within the document. Since all other resolvable UUIDs in Donlon are expressed as local references, these ones should be local, too.

### CODE REVIEW

**Comment by ttho** [comment]
I don't think this is a good idea as it could be interpreted differently. Local references point to concrete XML structures in the document, i.e. a feature in exactly that state as it is contained in the document. However, that state can change with later additions of time slices which are not in the document (which may change the past as well).
Abstract references, on the other hand, point to the feature object 'as it exists in the world' - which is independent of a representation known at the time when the document was created. 
At least that is my notion of abstract references.

**Comment by vog** [comment]
I see your point. My thinking was more about consistency.

Thinking more about this, wouldn't that mean Donlon should always use abstract references, and shouldn't contain local references at all?

**Comment by porosnie** [comment]
As Donlon is intended as test data, it might be useful to have both
- the master version with just abstract references
- a script (XSLT) that can detect internally present targets and transform the master into a version with internal references, when needed.
  I would favor a script versus maintaining two separate Donlon versions, one with internal and one with abstract references. That would simplify the maintenance.

**Comment by vog** [comment]
Such an XSLT script could also automatically check the referential integrity along the way, converting only those abstract references which are actually resolvable.

A related question is, how to we deal with non-resolvable abstract references in Donlon. However, that discussion would better fit into issue #2.

**Comment by porosnie** [comment]
As Donlon aims to be a complete sample, I think that it should not contain any non-resolvable abstract references.

**Comment by vog** [comment]
Okay, so I consider this one to be rejected, and created another pull request #11 to implement the idea of abstract references and the XSLT script.

I also created a new issue #12 regarding the unresolvable UUIDs.

**Pull request closed without merging**
