### PR TITLE
Replace references to Message metadata

### PR DESCRIPTION
**Pull request by vog**
Replace references to MessageContact, MessageCitation, MessagePOC and MessageConstraints (#20)

### CODE REVIEW

**Comment by porosnie** [comment]
Could we have the support of someone else for this, so that we can commit?

**Comment by vog** [comment]
Any opinions on this?

**Comment by manfredbeckmann** [comment]
If you could fix the typo "opreational" to "operational" within all occurrences of the "MessageConstraints" beforehand, I would support the change.

**Comment by vog** [comment]
Good catch! I fixed that, splitting the pull request into two commits: First, fix the typo. Then, the original change based on the fixed typo.

@manfredbeckmann: Please verify again.

**Comment by manfredbeckmann** [comment]
Thank's for the quick response, the splitted change is fine.

**Comment by vog** [comment]
@manfredbeckmann: Thanks for reviewing this!

@porosnie: If you support this, too, feel free to merge it. (According to our rules, I should not merge my own pull request.)

**Pull request merged**
